#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# BACKUP DATA DIRECTORY
#=================================================

ynh_backup --src_path="$data_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup von Beszel wurde erstellt!"

