#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE DATA DIRECTORY
#=================================================

# Stop service before restore
ynh_systemd_action --service_name=$app --action=stop

# Restore data directory
ynh_restore_file --origin_path="$data_dir"

# Set correct permissions
chown -R $app:$app "$data_dir"

# Start service
ynh_systemd_action --service_name=$app --action=start --log_path=systemd

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Beszel wurde erfolgreich wiederhergestellt!"

